name: Sync to Cloud Manager git repository

on: push

jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "adobe-basel/aem-project-template"
          source_branch: "refs/remotes/source/*"
          destination_repo: "https://${{ secrets.CM_GIT_USERNAME }}:${{ secrets.CM_GIT_PASSWORD }}@git.cloudmanager.adobe.com/stage-rdeteststage/RDEGW-p60706-uk13696"
          destination_branch: "refs/heads/*"