name: Create Cloud Manager Pipeline Execution

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

with:
  CLIENTID: ${{ secrets.CM_CLIENT_ID }}
  CLIENTSECRET: ${{ secrets.CM_CLIENT_SECRET }}
  TECHNICALACCOUNTID: ${{ secrets.CM_TA_EMAIL }}
  IMSORGID: ${{ secrets.CM_ORG_ID }}
  KEY: ${{ secrets.CM_PRIVATE_KEY }}
  PIPELINEID: ${{ secrets.CM_PIPELINE_ID }}
  PROGRAMID: ${{ secrets.CM_PROGRAM_ID }}

jobs:
  pipeline:
    steps:
      - name: Get or Create Cloud Manager Pipeline
        run: echo "Checking for existing Cloud Manager Pipeline for branch..."
      - name: Create Cloud Manager Pipeline Execution
        uses: adobe/aio-cloudmanager-create-execution-action@v1.0.5

